five-square/quickercater

package.json, server/db.js, server/server.js
Added create owner profile helper function
=> Created DB file

server/db.js, server/server.js, test/server/serverSpec.js
* Fleshed out the database reset function so that we can work with clean data.  No more manual deleting required, function does everything.  Changed wording and server endpoint to reflect this.
* Updated database dummy data with some additional relationships.  Orders should be modeled correctly.
* Added pending tests for Owner relationships with orders.  Will implement pending tests for Owner relationships with Items and Packages as soon as those server endpoints and database functions are implemented.
* Added a few database functions to handle adding and deleting relationships from Owner to any node (should work, need more tests to confirm).  Data validation is NOT present, duplicating data upon entry IS possible.  Be careful.
=> Added more tests for Owner implementation. Some database changes.

.eslintrc.js, client/components/App.js, client/models/serverAPI.js, package.json, server/db.js, server/server.js, test/server/serverSpec.js
* Consolidated database functions for creating and deleting nodes and relationships.
* Added serverAPI.js to client for consolidating request handling functions.
* Some simple changes to the front-end.
=> Changes to server.js, db.js, and client models.

client/components/App.js, client/components/Lobby.js, client/components/StoreCard.js, client/models/serverAPI.js, package.json, server/db.js
Updated Store Cards to included new data from the database
=> Feat lobby

server/db.js, test/server/serverSpec.js
=> Gh item crud

client/components/App.js, client/components/Lobby.js, client/components/StoreCard.js
compressed the store cards, and center aligned the cards. Cards still responsive.
=> Styled store cards

server/server.js
Endpoints look like they are working. But never can be sure.
=> Added endpoints for Item CRUD. No tests yet

client/components/App.js, client/components/MenuCard.js, client/components/ProfileEditor.js, client/main.js, client/models/serverAPI.js, server/db.js, server/server.js, test/server/serverSpec.js
* Adds ProfileEditor and MenuCard components
* Starts work on menu nodes and all the various things we must do for them
* Some other stuff, minor tweaks
=> Multiple commits

client/components/Dashboard.js, client/components/OrderTable.js
Merge me in right away so I don't conflict!
=> Started work on dashboard

client/components/Dashboard.js, client/components/OrderTable.js, client/components/StoreFront.js, client/models/orderAPI.js, server/db.js, server/server.js, test/client/clientSpec.js, test/server/serverSpec.js
Maybe wait until after presentation?
=> Order api gh

client/components/AddItemsButton.js, client/components/CompanyDescription.js, client/components/MenuCard.js, client/components/PackageCard.js, client/components/StoreFront.js, client/models/itemAPI.js, server/server.js
=> Fix add item

client/components/AddItemsButton.js
=> Fix add item card

client/components/AddItemsButton.js, client/components/AddPackageCard.js, client/components/App.js, client/components/ItemCard.js, client/components/MenuCard.js, client/components/PackageCard.js, client/components/StoreDescription.js, client/components/StoreFront.js, client/models/serverAPI.js, server/db.js, server/server.js
Replaced Image text field with image upload button and Image Preview
=> Updated Image Field

client/components/Dashboard.js, client/components/OrderTable.js, client/components/StoreFront.js, client/models/orderAPI.js, server/db.js, server/server.js
Continuing work on Dashboard component and pending/accepted order displays
=> Updates to Dashboard component. Starting connection to endpoint and db

client/components/App.js, client/components/Navigation.js, client/models/serverAPI.js, package.json, server/server.js
-Rearranged code in server.js
-updated package.json to remove passport as dependency and added authport
-Sign In and logout functionality working. On signIn a cookie(sessionId) is created. This will be user auth_key in db. On logout the cookie is destroyed.
=> Removed passport for authentication and added authport

client/components/App.js, client/components/Lobby.js, client/components/Navigation.js, client/models/cookieAPI.js
=> My store button gh

client/components/App.js, client/components/Navigation.js, client/models/serverAPI.js, server/db.js, server/server.js
=> Connects stores/owners on APPJS

client/components/OrderDetails.js, client/components/RegisterModal.js, client/components/StoreFront.js, client/models/orderAPI.js, server/db.js, server/server.js
creates and console logs object to be sent to db
=> Created registration modal

client/components/AddItemCard.js, client/components/EditItem.js, client/components/RegisterModal.js
added tooltip for drag and drop changed default image, added image preview on Edit Item modal
=> Updated Image Upload and Edit field

client/components/Dashboard.js, client/models/orderAPI.js, server/db.js, server/server.js
Added completed orders to dash
=> Complete orders on Dashboard

client/components/EditStore.js, client/components/StoreDescription.js, client/components/StoreFront.js, client/models/orderAPI.js
Now rendering the store description and can edit the description once
=> Feat store desc

client/components/App.js, client/components/Cart.js, client/components/PackageContainer.js, client/components/StoreFront.js
APP.JS now correct semantic naming for ownerId and ownerIdOfCurrentStore (regardless of actual user)
=> ready aim fire

client/components/App.js
=> Dash fixed now after ownerId fix

client/components/RegisterModal.js, client/components/StoreCard.js, client/components/StoreDescription.js
also added logo preview and upload banner option there but not required.
=> Update Style for Register Moda

client/components/EditStore.js, client/components/RegisterModal.js
For both Registration Modal and Edit Store Description Modal added a 200 character limit disabling the next or submit button if they go above the limit. It also gives the end user a count of remaining characters.
=> Add Character limit

client/components/Lobby.js, client/components/StoreCard.js, client/components/StoreDescription.js
Style store front and store description.
=> Style store front

client/components/Lobby.js, client/components/StoreCard.js
Can now filter by Food Category the caterer associates itself with.
=> Update Search Params

server/db.js, server/server.js
I Just added them back, I believe everything else is good to go
=> db.js comments almost done, just missing some menu and order functions

client/components/AddItemCard.js, client/components/AddMenuCard.js, client/components/App.js, client/components/EditStore.js, client/components/Navigation.js, client/components/RegisterModal.js, client/components/StoreDescription.js, client/components/StoreFront.js, client/models/ownerAPI.js, client/public/style.css, package.json, server/db.js
Now Able to update banner, and crop the image
=> Feat image update
